### ISSUE TITLE
Fix dash deployment on OpenShift, learn how to do so in the future.

### ISSUE THREAD

**Issue by JamesKunstle** [sandiego-rh/explorer#10]
Currently, a baby version of Dash Overview page is supposed to be deployed to OpenShift, with the help of Misc, but it's broken. Next steps are to fix this deployment and learn how to deploy on OpenShift in the future.

**Comment by JamesKunstle** [comment]
Update for today-
Misc and I had a conversation today. One of the problems that we were facing was that DockerHub was unable to serve our request for the docker image python 3.8.12-bullseye. However, we are able to use an open shift mirror of this image to circumvent this problem. 

Next step: when running the Docker container locally we mount the current directory as the project directory in the container. We need to switch this because OpenShift doesn't use the scripts that we are using to run the container locally. Therefore we actually need to copy the files into the working directory.

Additionally, since our goal is for this to be pseudo-prod we ought to remove the debug settings for the Dash instance when it's up which can be done with local/deployment  environment variables

**Comment by cdolfi** [comment]
TODO:

- [ ] Add augur login info as secrets
