### ISSUE TITLE
Get config parameters only from the environment rather than from config file

### ISSUE THREAD

**Issue by JamesKunstle** [sandiego-rh/explorer#138]
It would be better to get our credentials for our database from our environment rather than from a config file. However, this isn't as nice as it could be for distributing credentials- users would need to manually set their credentials and would need some experience working with Linux systems natively. 

Therefore, I think that there are some better steps that we could take here. On this account, we'll accomplish the following transition:

- [x] Describe standard format that could be used to distribute credentials (could be JSON)
- [x] Write a script to break those parameters out of the config file into the user's environment when developing locally
- [x] transition app from using a config file at all to only using environment variables.
- [x] document the preference thoroughly so that incoming users will understand how to use the new process.

**Comment by cdolfi** [comment]
@JamesKunstle can this be closed? I thought it was fixed in a prior pr but I might be mistaken
