### ISSUE TITLE
Question Should we change our page structure to use Dash's new page functionality 

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/explorer#26]
Discussion needed on if we should change our page structure to be consistent with dash documentation. Include conversation around using validation_layout

See resources: 
https://community.plotly.com/t/introducing-dash-pages-a-dash-2-x-feature-preview/57775
https://dash.plotly.com/urls
https://www.youtube.com/watch?v=RMBSQ6leonU
https://www.youtube.com/watch?v=sxGO1FAeQwU

**Comment by JamesKunstle** [comment]
This has been done on its own branch:

https://github.com/sandiego-rh/explorer/tree/dl-multipage-rework
