### ISSUE TITLE
Code/Repo Clean up

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/explorer#35]
After getting a little farther in the dash app, the following things need to be done to improve the repo and allow for better experience for new developers to come in: 

TODO:

- [x] Move db_interface folder 
- [x] clean up code that was created to use for repeating functions, make it applicable to what we know now 
- [x] made py file to have all call back code for queries to keep index page clean
- [x] add comments in index page explaining where the call backs are and how to add more 
- [x] update all of the in line comments for current app 
- [x] clean code from a design perspective (CSS, formatting) to make sure the code is all consistent

Notes on the last bullet point: We use a lot of different template code using different strategies with formatting (class_name, style, etc). Before things build too much, lets get this all consistent for when we build there is not weird format issue and we have items to use as templates

**Comment by JamesKunstle** [comment]
@cdolfi I think this issue is ready to be closed - let me know what you think.
