### ISSUE TITLE
Bug Fix: Connection to the Augur instance is severed in between calls.

### ISSUE THREAD

**Issue by JamesKunstle** [sandiego-rh/explorer#50]
The connection to Augur drops and causes a callback exception sometimes. Working on minimizing this problem with a pessimistic connection-checking process detailed in the sqlalchemy documentation using 'pre_pool_ping'.

**Comment by JamesKunstle** [comment]
This may have been solved by adding the flag:

```
        engine = salc.create_engine(
            database_connection_string,
            connect_args={"options": "-csearch_path={}".format(dbschema)},
            pool_pre_ping=True,
        )
```

**Comment by JamesKunstle** [comment]
This issue will likely be marked solved in the future if we cease to see problems with the connection to the Augur DB.

**Comment by cdolfi** [comment]
Closing for now
