### ISSUE TITLE
Search bar enhancements 

### ISSUE THREAD

**Issue by cdolfi** [sandiego-rh/explorer#98]
TODO: 

- [x] #105
- [ ] some type of prompt or assistance on if search term is not coming up

On the second part, there are two scenarios here. One, if there is a repo/org someone is looking for and it is in the set but they are not typing it correct. IE they are using the project name but that isnt exact to the repo/org. Some type of guidance to make sure the exact repo or org name is typed in would be good. Second, its not there and they need to be guided to open an issue for more projects to be loaded

**Comment by JamesKunstle** [comment]
Check out mantine components to potentially fix this

**Comment by cdolfi** [comment]
closed by #147
